spring:
  application:
    name: FlowStock-MS
  datasource:
    url: jdbc:mysql://localhost:3306/flowstock_db
    username: root
    password: '041105'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true